Repository stolostron/klusterlet-addon-operator, pull requests merged in 2021-04, with the labels that each got.

#10 Remove selfLink from policy chart
  helm-charts/policy/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
Labels: approved, lgtm

#8 update to v1 crds
  Makefile
  build/kind-config/kubernetes-v1.20.2_self_import.yaml
  build/run-functional-tests.sh
  deploy/crds-v1/agent.open-cluster-management.io_applicationmanagers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_certpolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_iampolicycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_policycontrollers_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_searchcollectors_crd.yaml
  deploy/crds-v1/agent.open-cluster-management.io_workmanagers_crd.yaml
  deploy/crds-v1/operator.open-cluster-management.io_multiclusterhub.crd.yaml
  deploy/crds/agent_v1beta1_applicationmanager_crd.yaml
  deploy/crds/agent_v1beta1_certmanager_crd.yaml
  deploy/crds/agent_v1beta1_monitoring_crd.yaml
  deploy/crds/agent_v1beta1_policycontroller_crd.yaml
  deploy/crds/agent_v1beta1_searchcollector_crd.yaml
  deploy/crds/agent_v1beta1_topology_collector_crd.yaml
  deploy/crds/agent_v1beta1_work_manager_crd.yaml
  deploy/crds/klusterlet_policy_controller_crd.yaml
  deploy/crds/klusterlet_search_collector_crd.yaml
  deploy/crds/klusterlet_work_manager_crd.yaml
  helm-charts/application-manager/templates/apps.open-cluster-management.io_deployable_crd.yaml
  helm-charts/application-manager/templates/apps.open-cluster-management.io_helmrelease_crd.yaml
  helm-charts/application-manager/templates/apps.open-cluster-management.io_subscriptions_crd.yaml
  helm-charts/cert-policy-controller/templates/certpolicy-crd.yaml
  helm-charts/iam-policy-controller/templates/iam-policy-controller-crd.yaml
  helm-charts/policy/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
  helm-charts/policy/templates/policy.open-cluster-management.io_policies_crd.yaml
Labels: approved, lgtm

#13 trigger build
  .triggerbuild
Labels: approved, dco-signoff: yes

#11 allow iam policy controller to create/update lease
  helm-charts/iam-policy-controller/templates/iam-policy-controller-clusterrole.yaml
  helm-charts/iam-policy-controller/templates/iam-policy-controller-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm

#12 allow cert policy controller to create/update lease
  helm-charts/cert-policy-controller/templates/deployment.yaml
  helm-charts/cert-policy-controller/templates/role.yaml
Labels: approved, dco-signoff: yes, lgtm

#14 remove extra space in args
  helm-charts/cert-policy-controller/templates/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm

#15 enable lease for policy-controller addon
  helm-charts/policy/templates/policy_framework_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm

#16 enable lease for config-policy-controller
  helm-charts/policy/templates/config_policy_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm

#17 Update policy.open-cluster-management.io_policies_crd.yaml
  helm-charts/policy/templates/policy.open-cluster-management.io_policies_crd.yaml
Labels: approved, dco-signoff: yes, lgtm

#18 update subscription v1 crd
  helm-charts/application-manager/templates/apps.open-cluster-management.io_subscriptions_crd.yaml
Labels: approved, dco-signoff: yes, lgtm
